### ISSUE TITLE
Rat?

### ISSUE THREAD

**Issue by Darkmonkey55** [pesshown/Skilled-Client-v3#2]
How do i know this is the legit version and not a rat or virus?  This isnt made by the owner of the client is it?

**Comment by pesshown** [comment]
Are you kidding me? Don't have any viruses, rat or malware, is open-source and you can open as edit the project in eclipse (or view code line by github), see with your own eyes the code line. I just add some features. ("only Weapon", "only clicking", "OnlyGround", "ignore water"...)
